# Generated by Django 3.0.4 on 2020-05-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_examen_crear_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenResuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.TextField(blank=True, default='', max_length=10000)),
                ('tema', models.TextField(blank=True, default='', max_length=10000)),
                ('tiempo', models.TextField(blank=True, default='', max_length=10000)),
                ('calificacion', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta1', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta2', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta3', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta4', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta5', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_calif', models.TextField(blank=True, default='', max_length=10000)),
            ],
        ),
    ]
