# Generated by Django 3.0.4 on 2020-05-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_examenresuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenresuelto',
            name='status_gsheet',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
